version: '3'

services:
  database:
    image: postgres:latest
    labels:
      app: 'wins-wp'
    container_name: wins_dev_pg
    restart: always
    environment:
      - POSTGRES_USER=GRAPHQL
      - POSTGRES_PASSWORD=manager
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '127.0.0.1:7431:5432'
