local-verify:
	pact-provider-verifier --provider-base-url=http://localhost:3003 --pact-broker-base-url=http://localhost:9291 --provider-app-version=1.0.0 --provider=NestJSGraphQL  # Match the provider name from your pact file
