local-verify:
	pact-provider-verifier --provider-base-url=http://localhost:3003 --pact-broker-base-url=http://localhost:9291 --provider=NestJSGraphQL --provider-app-version=1.0.0 --provider-states-setup-url=http://localhost:3003/pact-setup --publish-verification-results
