name: Pact CI/CD

on:
  push:
    branches: [main]

env:
  PACT_BROKER_BASE_URL: http://localhost:9292
  # PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }} # If auth enabled

jobs:
  consumer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./consumer
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Ruby
        run: sudo apt-get install ruby-full

      - name: Install pact_broker-client
        run: sudo gem install pact_broker-client

      - name: Start Pact Broker
        run: |
          docker run --network host -d \
            -e PACT_BROKER_DATABASE_ADAPTER=sqlite \
            -e PACT_BROKER_DATABASE_URL=sqlite::memory: \
            pactfoundation/pact-broker

      - name: Wait for Pact Broker to be ready
        run: |
          echo "Waiting for Pact Broker to be ready..."
          for i in {1..30}; do
            if nc -z localhost 9292; then
              echo "Pact Broker is ready!"
              break
            fi
            echo "Waiting... ($i)"
            sleep 2
          done

      - name: try curl instead
        run: |
          echo "Waiting for Pact Broker to be ready..."
          for i in {1..30}; do
            if curl --silent --head --connect-timeout 2 http://localhost:9292/diagnostic/status/heartbeat > /dev/null; then
              echo "Pact Broker is ready!"
              exit 0 # Exit script with success status
            fi
            echo "Waiting... ($i)"
            sleep 2 # Wait before retrying
          done

      - name: Install dependencies
        run: npm ci

      - name: Run consumer tests
        run: npm test

      - name: Publish Pact
        run: |
          pact-broker publish ./pact/pacts \
            --consumer-app-version=$GITHUB_SHA \
            --branch=$GITHUB_REF_NAME

      - name: Check if consumer can be deployed
        run: |
          pact-broker can-i-deploy \
            --pacticipant=NuxtBackend \
            --version=$GITHUB_SHA \
            --to-environment=prod

  provider:
    runs-on: ubuntu-latest
    needs: [consumer] # Wait for consumer job
    defaults:
      run:
        working-directory: ./provider
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Start provider
        run: npm run start & # Run in background

      - name: Verify pacts
        run: |
          pact-provider-verifier \
            --provider-base-url=http://localhost:3003 \
            --provider=NestJSGraphQL \
            --provider-app-version=$GITHUB_SHA \
            --publish-verification-results

      - name: Check if provider can be deployed
        run: |
          pact-broker can-i-deploy \
            --pacticipant=NestJSGraphQL \
            --version=$GITHUB_SHA \
            --to-environment=prod

      - name: Deploy to Prod
        if: success()
        run: ./echoSuccess.sh # Your deployment script
