name: Pact CI/CD

on:
  push:
    branches: [main]

env:
  PACT_BROKER_BASE_URL: http://pact-broker:9292

jobs:
  consumer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./consumer
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Ruby and pact_broker-client
        run: |
          sudo apt-get update
          sudo apt-get install ruby-full -y
          sudo gem install pact_broker-client

      - name: Create Docker Network
        run: docker network create pact-net

      - name: Start Pact Broker
        run: |
          docker run --network pact-net --name pact-broker -d \
            -e PACT_BROKER_DATABASE_ADAPTER=sqlite \
            -e PACT_BROKER_DATABASE_URL=sqlite::memory: \
            pactfoundation/pact-broker

      - name: Wait for Pact Broker to be ready
        run: |
          echo "Waiting for Pact Broker to be ready..."
          for i in {1..30}; do
            if curl --silent --head --connect-timeout 2 http://pact-broker:9292/diagnostic/status/heartbeat > /dev/null; then
              echo "Pact Broker is ready!"
              exit 0
            fi
            echo "Waiting... ($i)"
            sleep 2
          done
          echo "Pact Broker did not become ready in time."
          exit 1

      - name: Install dependencies
        run: npm ci

      - name: Run consumer tests
        run: npm test

      - name: Publish Pact
        run: |
          pact-broker publish ./pact/pacts \
            --consumer-app-version=$GITHUB_SHA \
            --branch=$GITHUB_REF_NAME

      - name: Check if consumer can be deployed
        run: |
          pact-broker can-i-deploy \
            --pacticipant=NuxtBackend \
            --version=$GITHUB_SHA \
            --to-environment=prod

  provider:
    runs-on: ubuntu-latest
    needs: [consumer]
    defaults:
      run:
        working-directory: ./provider
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Ruby and pact_broker-client
        run: |
          sudo apt-get update
          sudo apt-get install ruby-full -y
          sudo gem install pact_broker-client

      - name: Install dependencies
        run: npm ci

      - name: Start provider and verify pacts
        run: |
          npm run start & # Start provider in background
          sleep 5 # Give it a few seconds to boot
          pact-provider-verifier \
            --provider-base-url=http://localhost:3003 \
            --provider=NestJSGraphQL \
            --provider-app-version=$GITHUB_SHA \
            --publish-verification-results

      - name: Check if provider can be deployed
        run: |
          pact-broker can-i-deploy \
            --pacticipant=NestJSGraphQL \
            --version=$GITHUB_SHA \
            --to-environment=prod

      - name: Deploy to Prod
        if: success()
        run: ./echoSuccess.sh # Your deployment script
