name: Pact CI/CD

on:
  push:
    branches: [main]

env:
  PACT_BROKER_BASE_URL: http://localhost:9292

jobs:
  pact-test:
    runs-on: ubuntu-latest
    services:
      pact-broker:
        image: pactfoundation/pact-broker
        ports:
          - 9292:9292
        env:
          PACT_BROKER_DATABASE_ADAPTER: sqlite
          PACT_BROKER_DATABASE_URL: sqlite:///pact_broker.sqlite
          PACT_BROKER_PUBLIC_HEARTBEAT: 'true'
          PACT_BROKER_ALLOW_PUBLIC_READ: 'true'
      postgres:
        image: postgres:latest
        ports:
          - 7431:5432
        env:
          POSTGRES_USER: GRAPHQL
          POSTGRES_PASSWORD: manager
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Ruby
        run: sudo apt-get install ruby-full

      - name: Install pact_broker-client
        run: sudo gem install pact_broker-client

      - name: Install dependencies
        run: npm ci
        working-directory: ./consumer

      - name: Run consumer tests
        run: npm test
        working-directory: ./consumer

      - name: Publish Pact
        run: |
          pact-broker publish ./pact/pacts \
            --consumer-app-version=$GITHUB_SHA \
            --branch=$GITHUB_REF_NAME
        working-directory: ./consumer

      - name: Install provider dependencies
        run: npm ci
        working-directory: ./provider

      - name: Start provider
        run: npm run start &
        working-directory: ./provider

      - name: Install pact (provider verifier)
        run: sudo gem install pact-provider-verifier --no-document --force

      - name: Verify pacts
        run: |
          pact-provider-verifier \
            --provider-base-url=http://localhost:3003 \
            --pact-broker-base-url=$PACT_BROKER_BASE_URL \
            --provider=NestJSGraphQL \
            --provider-app-version=$GITHUB_SHA \
            --provider-states-setup-url=http://localhost:3003/pact-setup \
            --publish-verification-results
        working-directory: ./provider
